---
default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.29.0
  hooks:
  - id: yamllint
    args: [--format, parsable, --strict]

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --preserve-quotes]

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint-docker
    name: Lint Dockerfiles
    description: Runs hadolint Docker image to lint Dockerfiles
    language: docker_image
    types: ["dockerfile"]
    entry: ghcr.io/hadolint/hadolint hadolint

- repo: https://github.com/Calinou/pre-commit-luacheck
  rev: v1.0.0
  hooks:
  - id: luacheck
