---
name: linting

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./build/Dockerfile

    - uses: lunarmodules/luacheck@v1
